import type { Song } from '$lib';
import { TheLifeOfAShowgirlAlbum } from '$lib/releases/The Life of a Showgirl';

export const EldestDaughter: Song = {
	title: 'Eldest Daughter',
	release: TheLifeOfAShowgirlAlbum,
	lyrics: [
		"Everybody's so punk on the internet",
		"Everyone's unbothered til they're not",
		"Every joke's just trolling and memes",
		'Sad as it seems, apathy is hot',
		"Everybody's cutthroat in the comments",
		'Every single hot take is cold as ice',
		'When you found me I said I was busy',
		'That was a lie',
		'I have been afflicted by a terminal uniqueness',
		"I've been dying just from trying to seem cool",
		"But I'm not a bad bitch",
		"And this isn't savage",
		"But I'm never gonna let you down",
		"I'm never gonna leave you out",
		'So many traitors',
		'Smooth operators',
		"But I'm never gonna break that vow",
		"I'm never gonna leave you now, now, now",
		'You know the last time I laughed this hard was',
		"On the trampoline in somebody's backyard",
		"I must've been about 8 or 9",
		'That was the night I fell off and broke my arm',
		'Pretty soon I learned cautious discretion',
		'When your first crush crushes something kind',
		"When I said I don't believe in marriage",
		'That was a lie',
		'Every eldest daughter',
		'Was the first lamb to the slaughter',
		'So we all dressed up as wolves and we looked fire',
		"But I'm not a bad bitch,and this isn't savage",
		"But I'm never gonna let you down",
		"I'm never gonna leave you out",
		'So many traitors,smooth operators',
		"But I'm never gonna break that vow",
		"I'm never gonna leave you now,now,now",
		'We lie back',
		'A beautiful, beautiful time lapse',
		'Ferris wheels, kisses and lilacs',
		'And things I said were dumb',
		"'Cause I thought that I'd never find that beautiful,beautiful life that",
		'Shimmers that innocent light back',
		'Like when we were young',
		'Every youngest child felt',
		'They were raised up in the wild',
		"But now you're home",
		'"Cause I\'m not a bad bitch',
		"And this isn't savage",
		"And I'm never gonna let you down",
		"I'm never gonna leave you out",
		'So many traitors',
		'Smooth operators',
		"But I'm never gonna break that vow",
		"I'm never gonna leave you now, now, now",
		'Never gonna break that vow',
		'Never gonna leave you now',
		"Now I'm never gonna leave you now"
	]
};
