import type { Song } from '$lib';
import { TheLifeOfAShowgirlAlbum } from '$lib/releases/The Life of a Showgirl';

export const Honey: Song = {
	title: 'Honey',
	release: TheLifeOfAShowgirlAlbum,
	lyrics: [
		"You can call me 'honey' if you want",
		"Because I'm the one you want",
		"When anyone called me 'sweetheart'",
		'It was passive aggressive',
		'At the bar',
		"And the chick was telling me to 'back off'",
		'Cause her man had looked at me wrong',
		"If anyone called me 'honey'",
		'It was standing in the bathroom',
		'White teeth',
		"They were saying that skirt don't fit me",
		'And I cried the whole way home',
		'But you touch my face',
		'Redefine all of those blues',
		"When you say ... 'Honey'",
		'Summertime spritz, pink skies',
		"You can call me 'honey' if you want",
		"Because I'm the one you want",
		'Wintergreen kiss, all mine',
		'You give it different meaning, cause you mean it when you talk',
		"Honey, I'm home, we can play house",
		"We can bed down, pick me up, who's the baddest in the land, what's the plan?",
		"What's the plan? You could be my forever-night stand",
		'Honey',
		"When anyone called me 'sweetheart'",
		'It was passive aggressive',
		'At the bar',
		"And the chick was telling me to 'back off'",
		'Cause her man had looked at me wrong',
		"If anyone called me 'honey'",
		'It was standing in the bathroom',
		'White teeth',
		"They were saying that skirt don't fit me",
		'And I cried the whole way home',
		'But you touch my face',
		'Redefine all of those blues',
		'When you say ...',
		"You can call me 'honey' if you want",
		"Because I'm the one you want I'm the one you want",
		'You give it different meaning',
		'Cause you mean it when you talk',
		"Sweetie, it's yours, kicking in doors, take it to the floor, gimme more",
		'Buy the paint in the color of your eyes, of your eyes',
		'And graffiti my whole damn life',
		'Honey',
		'When anyone called me late night',
		'He was screwing around with my mind',
		'Asking, "What are you wearing?" too high',
		'To remember in the morning',
		"And when anyone called me 'lovely'",
		'They were finding ways not to praise me',
		"But you say it like you're in awe of me",
		'And you stay until the morning',
		'Honey',
		"When anyone called me 'sweetheart'",
		'It was passive aggressive',
		'At the bar',
		"And the chick was telling me to 'back off'",
		'Cause her man had looked at me wrong',
		"If anyone called me 'honey'",
		'It was standing in the bathroom',
		'White teeth',
		"They were saying that skirt don't fit me",
		'And I cried the whole way home',
		"But you can call me 'honey' if you want"
	]
};
