import type { Song } from '$lib';
import { TheLifeOfAShowgirlAlbum } from '$lib/releases/The Life of a Showgirl';

export const RuinTheFriendship: Song = {
	title: 'Ruin The Friendship',
	release: TheLifeOfAShowgirlAlbum,
	lyrics: [
		'Glistening grass from September rain',
		'Gray overpass full of neon names',
		'You drive, 85',
		'Gallatin Road and the lakeside beach',
		"Watching the game from your brother's Jeep",
		'Your smile, miles wide',
		'And it was not an invitation',
		"Should've kissed you anyway",
		"Should've kissed you anyway",
		'And it was not convenient, no',
		'But your girlfriend was away',
		"Should've kissed you anyway",
		'Shiny wood floors underneath my feet',
		'Disco ball makes everything look cheap',
		"Have fun, it's prom",
		'Wilted corsage dangles from my wrist',
		'Over his shoulder I catch a glimpse',
		'And see ... You looking at me',
		'And it was not an invitation',
		'But as the 50 Cent song played',
		"Should've kissed you anyway",
		'And it was not convenient, no',
		"Would've been the best mistake",
		"Should've kissed you anyway",
		"Don't make it awkward in second period",
		"Might piss your ex off, lately we've been good",
		'Staying friends is safe',
		"Doesn't mean you should",
		"Don't make it awkward in second period",
		"Might piss your ex off, lately we've been good",
		'Staying friends is safe',
		"Doesn't mean you should",
		'When I left school I lost track of you',
		'Abigail called me with the bad news',
		'Goodbye',
		"And we'll never know why",
		'It was not an invitation',
		'But I flew home anyway',
		'With so much left to say',
		'It was not convenient, no',
		'But I whispered at the grave',
		'"Should\'ve kissed you anyway"',
		'And it was not an invitation',
		"Should've kissed you anyway",
		"Should've kissed you anyway",
		'And it was not',
		'My advice is always ruin the friendship',
		'Better that than regret it',
		'For all time',
		"Should've kissed you anyway",
		'And my advice is always answer the question',
		'Better that than to ask it',
		'All your life',
		"Should've kissed you anyway",
		"Should've kissed you anyway"
	]
};
