import type { Song } from '$lib';
import { TheLifeOfAShowgirlAlbum } from '$lib/releases/The Life of a Showgirl';

export const WishList: Song = {
	title: 'Wi$h Li$t',
	release: TheLifeOfAShowgirlAlbum,
	lyrics: [
		'They want that yacht life',
		'Under chopper blades',
		'They want those bright lights and Balenci shades',
		'And a fat stack with a baby face',
		'They want it all',
		'They want that complex female character',
		"They want that critical smash Palme d'Or",
		'And an Oscar on their bathroom floor',
		'They want it all',
		'And they should have what they want',
		'They deserve what they want',
		'Hope they get what they want',
		'I just want you',
		'Have a couple kids',
		'Got the whole block looking like you',
		'We tell the world they gotta leave us alone ... and they do',
		'Wow',
		"Got me dreaming 'bout a driveway",
		'with a basketball hoop',
		'Boss up, settle down',
		'Got a wish list',
		'I just want you',
		'They want that freedom',
		'Living off the grid',
		'They want those three dogs that they call their kids',
		'And that good surf, no hypocrites',
		'They want it all',
		'They want a contract with Real Madrid',
		'They want that spring break where the clubs were lit - and then that video taken off the internet',
		'They want it all',
		'And they should have what they want',
		'They deserve what they want',
		'I hope they get what they want',
		'I just want you',
		'Have a couple kids',
		'Got the whole block looking like you',
		'We tell the world they gotta leave us alone ... and they do',
		'Wow',
		"Got me dreaming 'bout a driveway",
		'with a basketball hoop',
		'Boss up, settle down',
		'Got a wish list',
		'I made wishes on all of the stars',
		'Please, God bring me a best friend',
		'who I think is hot, I thought I had it right once, twice but I did not,',
		'you caught me off my guard',
		'I hope I get what I want',
		'Cause I know what I want',
		'I just want you',
		'Have a couple kids',
		'Got the whole block looking like you',
		'We tell the world they gotta leave us alone ... and they do',
		'Wow',
		"Got me dreaming 'bout a driveway",
		'with a basketball hoop',
		'Boss up, settle down',
		'Got a wish list',
		'I just want you',
		'Have a couple kids',
		'Got the whole block looking like you',
		'We tell the world they gotta leave us alone ... and they do',
		'Wow',
		"Got me dreaming 'bout a driveway",
		'with a basketball hoop',
		'Boss up, settle down',
		'Got a wish list',
		'I just want you'
	]
};
